version: '3.8'

services:
    redis-exercise27:
      image: redis
      container_name: redis-exercise27

    db-exercise27:
      image: postgres:13.2-alpine
      restart: unless-stopped
      volumes:
        - type: bind
          source: $HOST./data
          target: /var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: postgres
      container_name: db-exercise27

    frontend-exercise27:
      image: example-frontend:v3
      environment:
        - REACT_APP_BACKEND_URL=http://localhost:5051
      ports:
            - 5050:5000
      command: ["serve", "-s", "-l", "5000", "build"]
      container_name: frontend-exercise27

    backend-exercise27:
      image: example-backend:v3
      environment:
        - REQUEST_ORIGIN=http://localhost:5050
        - REDIS_HOST=redis-exercise27
        - REDIS_PORT=6379
        - POSTGRES_HOST=db-exercise27
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
      ports:
            - 5051:8080
      command: ["./server"]
      container_name: backend-exercise27