version: '3.8'

services:
    # Redis Memory DB
    redis-exercise29:
      image: redis
      container_name: redis-exercise29

    # Postgres SQL DB
    db-exercise29:
      image: postgres:13.2-alpine
      restart: unless-stopped
      volumes:
        - type: bind
          source: $HOST./data
          target: /var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: postgres
      container_name: db-exercise29

    # Frontend Server
    frontend-exercise29:
      image: example-frontend:v4
      environment:
        - REACT_APP_BACKEND_URL=http://localhost
      ports:
            - 5050:5000
      command: ["serve", "-s", "-l", "5000", "build"]
      container_name: frontend-exercise29

    # Backend Server
    backend-exercise29:
      image: example-backend:v3
      environment:
        - REQUEST_ORIGIN=http://localhost
        - REDIS_HOST=redis-exercise29
        - REDIS_PORT=6379
        - POSTGRES_HOST=db-exercise29
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
      ports:
            - 5051:8080
      command: ["./server"]
      container_name: backend-exercise29
    
    # Nginx ProxyPass Configuration
    nginx:
      image: nginx
      container_name: nginx-exercise29
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
          - 80:80
      depends_on: ["backend-exercise29", "frontend-exercise29"]
      